Visual Studio Code (1.93.0, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension Version: 2024.11.1.
Platform: linux (x64).
Temp Storage folder ~/.config/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder ~/hse/machine_learning, Home = /home/yoshee
11:50:20.675 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/hse/machine_learning/sem_8_classwork.ipynb' (disableUI=true)
11:50:20.696 [warn] Failed to get activated env vars for /bin/python3 in 21ms
11:50:20.706 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
11:50:20.708 [warn] Failed to get activated env vars for /bin/python3 in 24ms
11:50:20.727 [info] Process Execution: /bin/python3 -m pip list
11:50:20.736 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:50:20.738 [warn] Failed to get activated env vars for /bin/python3 in 27ms
11:50:20.747 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v310487cfb7917154465d858b39ececd789912100d.json
    > cwd: //home/~/hse/machine_learning
11:50:20.758 [info] Process Execution: /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:50:21.187 [info] Kernel successfully started
11:50:21.196 [info] Process Execution: /bin/python3 /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/pythonFiles/printJupyterDataDir.py
11:50:27.065 [info] Dispose Kernel '~/hse/machine_learning/sem_8_classwork.ipynb' associated with '~/hse/machine_learning/sem_8_classwork.ipynb'
11:50:27.169 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/hse/machine_learning/sem9_classwork.ipynb' (disableUI=true)
11:50:27.229 [warn] Failed to get activated env vars for /bin/python3 in 58ms
11:50:27.240 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:50:27.250 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v379c65cf6e28d04fa8266be876484d5ea714ba73d.json
    > cwd: //home/~/hse/machine_learning
11:50:28.100 [info] Kernel successfully started
11:59:31.594 [warn] Cell completed with errors nu [Error]: name 'data' is not defined
    at n.execute (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'NameError',
  evalue: "name 'data' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[1], line 2\x1B[0m\n' +
      "\x1B[1;32m      1\x1B[0m \x1B[38;5;66;03m# data['InvoiceNo'] = data['InvoiceNo'].astype('int')\x1B[39;00m\n" +
      "\x1B[0;32m----> 2\x1B[0m data \x1B[38;5;241m=\x1B[39m \x1B[43mdata\x1B[49m[data[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mQuantity\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m>\x1B[39m \x1B[38;5;241m0\x1B[39m]\n" +
      "\x1B[1;32m      3\x1B[0m data \x1B[38;5;241m=\x1B[39m data[data[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mUnitPrice\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m>\x1B[39m \x1B[38;5;241m0\x1B[39m]\n",
    "\x1B[0;31mNameError\x1B[0m: name 'data' is not defined"
  ]
}
11:59:37.417 [warn] Cell completed with errors nu [Error]: name 'pd' is not defined
    at n.execute (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'NameError',
  evalue: "name 'pd' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[2], line 2\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;66;03m#посмотрим на данные\x1B[39;00m\n' +
      "\x1B[0;32m----> 2\x1B[0m data \x1B[38;5;241m=\x1B[39m \x1B[43mpd\x1B[49m\x1B[38;5;241m.\x1B[39mread_csv(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m./DataSet_france.csv\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[1;32m      3\x1B[0m data\x1B[38;5;241m.\x1B[39mhead(\x1B[38;5;241m5\x1B[39m)\n',
    "\x1B[0;31mNameError\x1B[0m: name 'pd' is not defined"
  ]
}
12:02:01.714 [warn] Cell completed with errors nu [Error]: unhashable type: 'list'
    at n.execute (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'TypeError',
  evalue: "unhashable type: 'list'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mTypeError\x1B[0m                                 Traceback (most recent call last)',
    '\x1B[0;32m/tmp/ipykernel_9634/3792930082.py\x1B[0m in \x1B[0;36m?\x1B[0;34m()\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0;31m \x1B[0mdata\x1B[0m \x1B[0;34m=\x1B[0m \x1B[0mdata\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0mloc\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0;34m[\x1B[0m\x1B[0mdata\x1B[0m\x1B[0;34m[\x1B[0m\x1B[0;34m'Description'\x1B[0m\x1B[0;34m]\x1B[0m \x1B[0;34m!=\x1B[0m \x1B[0;34m'POSTAGE'\x1B[0m\x1B[0;34m]\x1B[0m\x1B[0;34m)\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n" +
      '\x1B[0m',
    '\x1B[0;32m/usr/lib/python3.12/site-packages/pandas/core/indexing.py\x1B[0m in \x1B[0;36m?\x1B[0;34m(self, axis)\x1B[0m\n' +
      '\x1B[1;32m    734\x1B[0m         \x1B[0;31m# we need to return a copy of ourselves\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    735\x1B[0m         \x1B[0mnew_self\x1B[0m \x1B[0;34m=\x1B[0m \x1B[0mtype\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0mself\x1B[0m\x1B[0;34m)\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0mself\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0mname\x1B[0m\x1B[0;34m,\x1B[0m \x1B[0mself\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0mobj\x1B[0m\x1B[0;34m)\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    736\x1B[0m \x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    737\x1B[0m         \x1B[0;32mif\x1B[0m \x1B[0maxis\x1B[0m \x1B[0;32mis\x1B[0m \x1B[0;32mnot\x1B[0m \x1B[0;32mNone\x1B[0m\x1B[0;34m:\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[0;32m--> 738\x1B[0;31m             \x1B[0maxis_int_none\x1B[0m \x1B[0;34m=\x1B[0m \x1B[0mself\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0mobj\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0m_get_axis_number\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0maxis\x1B[0m\x1B[0;34m)\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[0m\x1B[1;32m    739\x1B[0m         \x1B[0;32melse\x1B[0m\x1B[0;34m:\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    740\x1B[0m             \x1B[0maxis_int_none\x1B[0m \x1B[0;34m=\x1B[0m \x1B[0maxis\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    741\x1B[0m         \x1B[0mnew_self\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0maxis\x1B[0m \x1B[0;34m=\x1B[0m \x1B[0maxis_int_none\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n',
    '\x1B[0;32m/usr/lib/python3.12/site-packages/pandas/core/generic.py\x1B[0m in \x1B[0;36m?\x1B[0;34m(cls, axis)\x1B[0m\n' +
      '\x1B[1;32m    573\x1B[0m     \x1B[0;34m@\x1B[0m\x1B[0mclassmethod\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    574\x1B[0m     \x1B[0;32mdef\x1B[0m \x1B[0m_get_axis_number\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0mcls\x1B[0m\x1B[0;34m,\x1B[0m \x1B[0maxis\x1B[0m\x1B[0;34m:\x1B[0m \x1B[0mAxis\x1B[0m\x1B[0;34m)\x1B[0m \x1B[0;34m->\x1B[0m \x1B[0mAxisInt\x1B[0m\x1B[0;34m:\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    575\x1B[0m         \x1B[0;32mtry\x1B[0m\x1B[0;34m:\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[1;32m    576\x1B[0m             \x1B[0;32mreturn\x1B[0m \x1B[0mcls\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0m_AXIS_TO_AXIS_NUMBER\x1B[0m\x1B[0;34m[\x1B[0m\x1B[0maxis\x1B[0m\x1B[0;34m]\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[0;32m--> 577\x1B[0;31m         \x1B[0;32mexcept\x1B[0m \x1B[0mKeyError\x1B[0m\x1B[0;34m:\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n' +
      '\x1B[0m\x1B[1;32m    578\x1B[0m             \x1B[0;32mraise\x1B[0m \x1B[0mValueError\x1B[0m\x1B[0;34m(\x1B[0m\x1B[0;34mf"\x1B[0m\x1B[0;34mNo axis named \x1B[0m\x1B[0;34m{\x1B[0m\x1B[0maxis\x1B[0m\x1B[0;34m}\x1B[0m\x1B[0;34m for object type \x1B[0m\x1B[0;34m{\x1B[0m\x1B[0mcls\x1B[0m\x1B[0;34m.\x1B[0m\x1B[0m__name__\x1B[0m\x1B[0;34m}\x1B[0m\x1B[0;34m"\x1B[0m\x1B[0;34m)\x1B[0m\x1B[0;34m\x1B[0m\x1B[0;34m\x1B[0m\x1B[0m\n',
    "\x1B[0;31mTypeError\x1B[0m: unhashable type: 'list'"
  ]
}
20:20:53.934 [info] Dispose Kernel '~/hse/machine_learning/sem_8_classwork.ipynb' associated with '~/hse/machine_learning/sem_8_classwork.ipynb'
20:20:53.934 [info] Dispose Kernel '~/hse/machine_learning/sem9_classwork.ipynb' associated with '~/hse/machine_learning/sem9_classwork.ipynb'
20:20:53.973 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v379c65cf6e28d04fa8266be876484d5ea714ba73d.json for pid 9634 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
